spring:
    datasource:

        url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 03112002Ayoub
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      database: MYSQL
      show-sql: false
      hibernate:
            ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 8081

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    enabled=true:

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            mvc:
#              method:
#                annotation=DEBUG: true